remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: nick brown on github
description: security research, pentesting tools, LLM, and superfluous emojis

